import { useState } from 'react';

// --- DUMMY DATA FOR TESTING ---
const MOCK_COMPONENTS = [
  {
    id: "comp-1",
    title: "Modern User Profile Card",
    category: "Cards",
    likes: "2.1k",
    views: "8.5k",
    author: "@codeai_gen",
    description: "A sleek, glassmorphism profile card with a glowing follow button and floating stats.",
    code: `import React from 'react';\n\nconst ProfileCard = () => {\n  return (\n    <div className="p-6 bg-white/5 backdrop-blur-xl border border-white/10 rounded-2xl">\n      {/* Code generated by AI */}\n      <h3 className="text-emerald-400">Profile Card</h3>\n    </div>\n  );\n};\n\nexport default ProfileCard;`,
    preview: (
      <div className="relative group p-6 bg-linear-to-br from-emerald-900/40 to-[#00140a] backdrop-blur-md border border-emerald-500/20 rounded-2xl hover:border-emerald-500/50 transition-all duration-300 w-full sm:w-80 shadow-[0_0_30px_rgba(16,185,129,0.1)]">
        <div className="flex items-center gap-4 mb-4">
          <div className="w-12 h-12 rounded-full bg-emerald-500/20 border border-emerald-500/50 animate-pulse-slow"></div>
          <div>
            <h4 className="text-slate-200 font-semibold text-sm sm:text-base">Tanishk Namdev</h4>
            <p className="text-emerald-400/80 text-xs">@developer</p>
          </div>
        </div>
        <button className="w-full py-2 bg-emerald-500/10 text-emerald-400 border border-emerald-500/30 rounded-lg hover:bg-emerald-500 hover:text-[#000502] transition-all font-medium text-sm shadow-[0_0_15px_rgba(16,185,129,0.2)]">Follow</button>
      </div>
    )
  },
  {
    id: "comp-2",
    title: "Pill-Shaped Floating Navbar",
    category: "Navbars",
    likes: "1.8k",
    views: "5.2k",
    author: "@codeai_gen",
    description: "A fully responsive, sticky floating navbar with CSS-only hover states and a glowing sign-up button.",
    code: `import React from 'react';\n\nconst Navbar = () => {\n  return (\n    <nav className="fixed top-4 left-1/2 -translate-x-1/2 bg-white/5 backdrop-blur-md... ">\n      {/* Navbar Code */}\n    </nav>\n  );\n};\n\nexport default Navbar;`,
    preview: (
      <div className="flex items-center justify-between px-4 sm:px-6 py-3 bg-[#00140a]/80 backdrop-blur-xl border border-white/10 rounded-full w-full max-w-[18rem] sm:max-w-md shadow-2xl">
        <div className="text-emerald-400 font-bold tracking-widest text-xs sm:text-sm">LOGO.</div>
        <div className="flex gap-2 sm:gap-4 text-[10px] sm:text-xs text-slate-300 font-medium">
          <span className="hover:text-emerald-400 cursor-pointer transition-colors">Home</span>
          <span className="hover:text-emerald-400 cursor-pointer transition-colors">Features</span>
        </div>
        <button className="px-3 sm:px-4 py-1.5 bg-emerald-500 rounded-full text-[#000502] text-[10px] sm:text-xs font-bold hover:scale-105 transition-transform">Sign Up</button>
      </div>
    )
  },
  {
    id: "comp-3",
    title: "Holographic Credit Card",
    category: "Cards",
    likes: "3.4k",
    views: "12k",
    author: "@codeai_gen",
    description: "Futuristic 3D tilt-effect credit card with animated gradients and glossy reflections.",
    code: `import React from 'react';\n\nconst HoloCard = () => {\n  return (\n    <div className="w-96 h-56 bg-linear-to-tr from-fuchsia-500/20 to-cyan-500/20...">\n      {/* Holo Card Code */}\n    </div>\n  );\n};\n\nexport default HoloCard;`,
    preview: (
      <div className="w-full sm:w-80 h-40 sm:h-48 rounded-2xl bg-linear-to-tr from-indigo-500/20 via-purple-500/20 to-emerald-500/20 p-px relative overflow-hidden group">
        <div className="absolute inset-0 bg-linear-to-tr from-white/5 to-transparent opacity-0 group-hover:opacity-100 transition-opacity duration-700 pointer-events-none"></div>
        <div className="w-full h-full bg-[#000502]/80 backdrop-blur-xl rounded-2xl p-4 sm:p-6 flex flex-col justify-between">
           <div className="w-8 h-6 sm:w-10 sm:h-8 rounded bg-yellow-500/20 border border-yellow-500/50"></div>
           <div className="text-slate-200 tracking-widest sm:tracking-[0.2em] font-mono text-base sm:text-lg">**** **** **** 4092</div>
           <div className="flex justify-between text-[10px] sm:text-xs text-slate-400 uppercase"><span>Tanishk N.</span><span>12/28</span></div>
        </div>
      </div>
    )
  }
];

const Components = () => {

    // ------------- UseStates ---------------
    const [activeComponent, setActiveComponent] = useState(MOCK_COMPONENTS[0]);
    const [activeTab, setActiveTab] = useState('preview'); 

  return (

    <div className="flex flex-col md:flex-row h-dvh w-full bg-[#000502] text-slate-200 font-sans overflow-hidden relative">
      
        {/* ------- Background Glow Effect ------- */}
        <div className="absolute top-[-10%] left-[-10%] w-[40%] h-[40%] bg-emerald-500/10 blur-[120px] rounded-full pointer-events-none"></div>
        <div className="absolute bottom-[-10%] right-[-10%] w-[40%] h-[40%] bg-cyan-500/10 blur-[120px] rounded-full pointer-events-none"></div>

        {/* ------------ SIDEBAR ----------------- */}
        {/* -Sidebar with components & search bar- */}
        <aside className="w-full md:w-80 h-auto md:h-full shrink-0 border-b md:border-b-0 md:border-r border-white/5 bg-[#00140a]/40 backdrop-blur-xl flex flex-col z-10">
            
            <div className="p-4 md:p-6 border-b border-white/5">
                <h2 className="text-lg md:text-xl font-bold bg-clip-text text-transparent bg-linear-to-r from-emerald-400 to-cyan-400 mb-3 md:mb-4">
                    Component.io
                </h2>
                {/* ----- Search Bar ------ */}
                <div className="relative">
                    <input 
                    type="text" 
                    placeholder="Search components..." 
                    className="w-full bg-[#000502] border border-emerald-900/50 rounded-lg py-2 pl-10 pr-4 text-sm text-slate-300 focus:outline-none focus:border-emerald-500/50 transition-colors placeholder-slate-600"
                    />
                    <svg className="w-4 h-4 absolute left-3 top-2.5 text-slate-500" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z"></path></svg>
                </div>
            </div>

            {/* -------- Components Lists ------- */}
            {/* ----------- Components ---------- */}
            <div className="flex md:flex-1 overflow-x-auto md:overflow-y-auto flex-row md:flex-col p-3 md:p-4 gap-3 md:gap-0 md:space-y-2 custom-scrollbar">
                {/* ---- Map to render all components ---- */}
                {MOCK_COMPONENTS.map((comp) => (
                    <button
                    key={comp.id}
                    onClick={() => setActiveComponent(comp)}
                    className={`shrink-0 w-64 md:w-full text-left px-4 py-3 rounded-xl transition-all duration-300 flex flex-col gap-1 border ${
                        activeComponent.id === comp.id 
                        ? 'bg-emerald-900/20 border-emerald-500/30 shadow-[inset_4px_0_0_0_#10b981]' 
                        : 'bg-transparent border-white/5 md:border-transparent hover:bg-white/5'
                    }`}
                    >
                    <span className={`text-sm font-semibold truncate ${activeComponent.id === comp.id ? 'text-emerald-400' : 'text-slate-300'}`}>
                        {comp.title}
                    </span>
                    <span className="text-xs text-slate-500">{comp.category}</span>
                    </button>
                ))}
            </div>

        </aside>

        {/* --------- Main Content Area ---------- */}
        {/* --------- Header/Code/Preview -------- */}
        <main className="flex-1 overflow-hidden flex flex-col z-10 relative">

            {/* -------- Main Content Header -------- */}
            <header className="mt-2 h-auto md:h-20 border-b border-white/5 p-4 md:px-8 flex flex-col md:flex-row items-start md:items-center justify-between gap-4 md:gap-0 bg-[#00140a]/20 backdrop-blur-md shrink-0">
                <div className="w-full md:w-auto">
                    <h1 className="text-xl md:text-2xl font-bold text-slate-100 truncate">{activeComponent.title}</h1>
                    <div className="flex flex-wrap items-center gap-3 md:gap-4 mt-2 md:mt-1 text-xs font-medium text-slate-400">
                        <span className="text-emerald-500 bg-emerald-500/10 px-2 py-0.5 rounded uppercase tracking-wider">{activeComponent.category}</span>
                        <span className="flex items-center gap-1"> 💚{activeComponent.likes}</span>
                        <span className="flex items-center gap-1"> 👁️{activeComponent.views}</span>
                    </div>
                </div>
            
                <div className="flex gap-2 md:gap-3 w-full md:w-auto mt-2 md:mt-0">
                    <button className="flex-1 md:flex-none justify-center px-3 md:px-4 py-2 rounded-lg bg-white/5 border border-white/10 text-xs md:text-sm font-medium hover:bg-white/10 transition-colors flex items-center gap-2">
                        Copy Code
                    </button>
                    <button className="flex-1 md:flex-none justify-center px-3 md:px-4 py-2 rounded-lg bg-emerald-600 hover:bg-emerald-500 text-white border border-emerald-500 text-xs md:text-sm font-medium transition-all shadow-[0_0_15px_rgba(16,185,129,0.3)]">
                        Save
                    </button>
                </div>
            </header>


            {/* ------- Main WorkSpace Area -------- */}
            {/* ------ Code / Preview / Footer ----- */}
            <div className="flex-1 overflow-hidden flex flex-col p-4 md:p-6">
            
                {/* ----- Tabs ----- */}
                <div className="flex gap-1 md:gap-2 p-1 bg-[#00140a] border border-white/10 rounded-xl w-fit mb-3 md:mb-4 mx-auto md:mx-0">
                    <button 
                    onClick={() => setActiveTab('preview')}
                    className={`px-5 md:px-6 py-1.5 rounded-lg text-xs md:text-sm font-medium transition-all ${activeTab === 'preview' ? 'bg-white/10 text-emerald-400 shadow-sm' : 'text-slate-400 hover:text-slate-200'}`}
                    >
                        Preview
                    </button>
                    <button 
                    onClick={() => setActiveTab('code')}
                    className={`px-5 md:px-6 py-1.5 rounded-lg text-xs md:text-sm font-medium transition-all ${activeTab === 'code' ? 'bg-white/10 text-emerald-400 shadow-sm' : 'text-slate-400 hover:text-slate-200'}`}
                    >
                        Code
                    </button>
                </div>

                {/* -------- Render Area --------- */}
                {/* -------- Code & Preview ------ */}
                <div className="flex-1 bg-[#000502]/80 border border-white/5 rounded-xl md:rounded-2xl overflow-hidden relative backdrop-blur-sm shadow-2xl flex items-center justify-center">
                    
                    {/* --- Background Effect --- */}
                    {activeTab === 'preview' && (
                    <div className="absolute inset-0 opacity-[0.03] pointer-events-none" style={{ backgroundImage: 'radial-gradient(circle at 2px 2px, white 1px, transparent 0)', backgroundSize: '24px 24px' }}></div>
                    )}

                    {/* ------- Preview Area ------ */}
                    {/* ---- Component Preview ---- */}
                    {activeTab === 'preview' && (
                        <div className="relative z-10 w-full h-full flex items-center justify-center p-4 md:p-8 overflow-auto">
                            {activeComponent.preview}
                        </div>
                    )}

                    {/* ------- Code Area ---------- */}
                    {/* ------ Component Code ------ */}
                    {activeTab === 'code' && (
                    <div className="w-full h-full bg-[#0d1117] overflow-auto p-4 md:p-6 relative">
                        <div className="absolute top-2 right-2 md:top-4 md:right-4 text-[10px] md:text-xs text-slate-500 font-mono">React / Tailwind</div>
                        <pre className="text-xs md:text-sm font-mono text-emerald-300/80 leading-relaxed whitespace-pre-wrap sm:whitespace-pre">
                        <code>{activeComponent.code}</code>
                        </pre>
                    </div>
                    )}

                </div>

                {/* -- Component Details Footer --- */}
                <div className="mt-3 md:mt-4 p-3 md:p-4 rounded-xl bg-white/5 border border-white/5 flex flex-col sm:flex-row gap-3 md:gap-4 items-start sm:items-center">
                    <div className="hidden sm:flex shrink-0 w-10 h-10 rounded-full bg-linear-to-tr from-emerald-500 to-cyan-500 p-px">
                        <div className="w-full h-full bg-[#000502] rounded-full flex items-center justify-center text-xs font-bold">AI</div>
                    </div>
                    <div>
                        <p className="text-xs md:text-sm text-slate-300 leading-snug">{activeComponent.description}</p>
                        <p className="text-[10px] md:text-xs text-slate-500 mt-1 md:mt-1.5">Generated by <span className="text-emerald-500/80">{activeComponent.author}</span> • Uses Tailwind CSS</p>
                    </div>
                </div>

            </div>

        </main>

    </div>

  );
};

export default Components;