import { useState } from 'react';

// ------- Dummy User Data  --------
const USER_PROFILE = {
  name: "Tanishk Namdev",
  email: "tanishk@developer.io",
  avatar: "TN",
  isVerified: true,
  credits: 1450,
  callsMade: 342,
  tier: "Pro Developer"
};

// ----- Dummy Saved Components -----
const SAVED_COMPONENTS = [
  {
    id: "comp-1",
    title: "Modern User Profile Card",
    category: "Cards",
    dateSaved: "Oct 24, 2026",
    code: `import React from 'react';\n\nconst ProfileCard = () => {\n  return (\n    <div className="p-6 bg-white/5 backdrop-blur-xl border border-white/10 rounded-2xl">\n      {/* Code generated by AI */}\n      <h3 className="text-emerald-400">Profile Card</h3>\n    </div>\n  );\n};\n\nexport default ProfileCard;`,
    preview: (
      <div className="relative p-6 bg-gradient-to-br from-emerald-900/40 to-[#00140a] backdrop-blur-md border border-emerald-500/20 rounded-2xl w-full sm:w-80 shadow-2xl">
        <div className="flex items-center gap-4 mb-4">
          <div className="w-12 h-12 rounded-full bg-emerald-500/20 border border-emerald-500/50 flex items-center justify-center text-emerald-400 font-bold">TN</div>
          <div>
            <h4 className="text-slate-200 font-semibold text-sm sm:text-base">Tanishk Namdev</h4>
            <p className="text-emerald-400/80 text-xs">@developer</p>
          </div>
        </div>
        <button className="w-full py-2 bg-emerald-500/10 text-emerald-400 border border-emerald-500/30 rounded-lg text-sm">Follow</button>
      </div>
    )
  },
  {
    id: "comp-2",
    title: "Pill-Shaped Floating Navbar",
    category: "Navbars",
    dateSaved: "Oct 22, 2026",
    code: `import React from 'react';\n\nconst Navbar = () => {\n  return (\n    <nav className="fixed top-4 left-1/2 -translate-x-1/2 bg-white/5 backdrop-blur-md... ">\n      {/* Navbar Code */}\n    </nav>\n  );\n};\n\nexport default Navbar;`,
    preview: (
      <div className="flex items-center justify-between px-4 sm:px-6 py-3 bg-[#00140a]/80 backdrop-blur-xl border border-white/10 rounded-full w-full max-w-md shadow-2xl">
        <div className="text-emerald-400 font-bold tracking-widest text-xs sm:text-sm">LOGO.</div>
        <div className="flex gap-4 text-xs text-slate-300 font-medium">
          <span className="text-emerald-400">Home</span>
          <span>Features</span>
        </div>
        <button className="px-4 py-1.5 bg-emerald-500 rounded-full text-[#000502] text-xs font-bold">Sign Up</button>
      </div>
    )
  }
];


const Profile = () => {

    // ----------- UseStates -------------
    const [activeComponent, setActiveComponent] = useState(SAVED_COMPONENTS[0]);
    const [activeTab, setActiveTab] = useState('preview'); // 'preview' or 'code'


  return (

    <div className="min-h-screen w-full bg-[#000502] text-slate-200 font-sans overflow-y-auto relative flex flex-col">
      
        {/* ----- Background Glow Effect ----- */}
        <div className="fixed top-[-10%] left-[-10%] w-[40%] h-[40%] bg-emerald-500/10 blur-[120px] rounded-full pointer-events-none"></div>
        <div className="fixed bottom-[-10%] right-[-10%] w-[40%] h-[40%] bg-cyan-500/10 blur-[120px] rounded-full pointer-events-none"></div>


        {/* ------ Main Content Section ------- */}
        <div className="max-w-7xl w-full mx-auto p-4 md:p-8 flex flex-col gap-6 lg:gap-8 z-10 flex-1">
        
            {/* --- Profile Header Section --- */}
            <section className="bg-[#00140a]/60 backdrop-blur-xl border border-white/10 rounded-3xl p-6 md:p-8 flex flex-col lg:flex-row items-center lg:items-start justify-between gap-8 shadow-2xl relative overflow-hidden">
                
                <div className="absolute top-0 right-0 w-64 h-64 bg-emerald-500/5 blur-[80px] rounded-full pointer-events-none"></div>

                {/* ---- User Left Info ----- */}
                <div className="flex flex-col sm:flex-row items-center sm:items-start gap-6 w-full lg:w-auto text-center sm:text-left">
                    {/* Avatar */}
                    <div className="w-24 h-24 rounded-full bg-linear-to-tr from-emerald-500 to-cyan-500 p-1 shadow-[0_0_30px_rgba(16,185,129,0.2)]">
                        <div className="w-full h-full bg-[#000502] rounded-full flex items-center justify-center text-3xl font-bold text-slate-100">
                        {USER_PROFILE.avatar}
                        </div>
                    </div>

                    {/* Details */}
                    <div className="flex flex-col justify-center h-full pt-1">
                        <div className="flex items-center justify-center sm:justify-start gap-3 mb-1">
                            <h1 className="text-2xl md:text-3xl font-bold text-white">{USER_PROFILE.name}</h1>
                            {USER_PROFILE.isVerified && (
                            <span className="flex items-center gap-1 bg-emerald-500/10 text-emerald-400 border border-emerald-500/20 px-2.5 py-1 rounded-full text-[10px] font-bold uppercase tracking-wide">
                                <svg className="w-3 h-3" fill="currentColor" viewBox="0 0 20 20"><path fillRule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.707-9.293a1 1 0 00-1.414-1.414L9 10.586 7.707 9.293a1 1 0 00-1.414 1.414l2 2a1 1 0 001.414 0l4-4z" clipRule="evenodd"></path></svg>
                                Verified
                            </span>
                            )}
                        </div>

                        <p className="text-slate-400 text-sm mb-4">{USER_PROFILE.email}</p>
                    
                        <div className="flex items-center gap-3 justify-center sm:justify-start">
                            <span className="px-3 py-1 bg-white/5 border border-white/10 rounded-lg text-xs font-medium text-slate-300">{USER_PROFILE.tier}</span>
                            <button className="px-4 py-1 bg-rose-500/10 text-rose-400 border border-rose-500/20 hover:bg-rose-500/20 rounded-lg text-xs font-medium transition-colors flex items-center gap-2">
                            <svg className="w-3.5 h-3.5" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M17 16l4-4m0 0l-4-4m4 4H7m6 4v1a3 3 0 01-3 3H6a3 3 0 01-3-3V7a3 3 0 013-3h4a3 3 0 013 3v1"></path></svg>
                            Logout
                            </button>
                        </div>
                    </div>

                </div>

                {/* --- User Right Info (Stats) --- */}
                <div className="grid grid-cols-2 sm:grid-cols-3 gap-3 md:gap-4 w-full lg:w-auto">
                    <div className="bg-[#000502]/50 border border-white/5 rounded-2xl p-4 flex flex-col justify-center items-center lg:items-start text-center lg:text-left">
                        <span className="text-emerald-400 text-xs font-bold uppercase tracking-wider mb-1 flex items-center gap-1.5"><svg className="w-3.5 h-3.5" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M13 10V3L5 14l3-4L6 17v7l8-11z"></path></svg> Credits</span>
                        <span className="text-2xl font-bold text-white">{USER_PROFILE.credits}</span>
                    </div>
                    <div className="bg-[#000502]/50 border border-white/5 rounded-2xl p-4 flex flex-col justify-center items-center lg:items-start text-center lg:text-left">
                        <span className="text-cyan-400 text-xs font-bold uppercase tracking-wider mb-1 flex items-center gap-1.5"><svg className="w-3.5 h-3.5" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M8 9l3 3-3 3m5 0h3M5 20h14a2 2 0 002-2V6a2 2 0 00-2-2H5a2 2 0 00-2 2v12a2 2 0 002 2z"></path></svg> API Calls</span>
                        <span className="text-2xl font-bold text-white">{USER_PROFILE.callsMade}</span>
                    </div>
                    <div className="bg-[#000502]/50 border border-white/5 rounded-2xl p-4 flex flex-col justify-center items-center lg:items-start text-center lg:text-left col-span-2 sm:col-span-1">
                        <span className="text-purple-400 text-xs font-bold uppercase tracking-wider mb-1 flex items-center gap-1.5"><svg className="w-3.5 h-3.5" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M5 8h14M5 8a2 2 0 110-4h14a2 2 0 110 4M5 8v10a2 2 0 002 2h10a2 2 0 002-2V8m-9 4h4"></path></svg> Saved</span>
                        <span className="text-2xl font-bold text-white">{SAVED_COMPONENTS.length}</span>
                    </div>
                </div>

            </section>

        
            {/* ------ Saved Components ------- */}
            {/* --- User's Saved Components --- */}
            <section className="flex flex-col h-full flex-1 min-h-150">
            
                <h2 className="text-xl font-bold text-slate-100 mb-4 flex items-center gap-2">
                    My Saved Components
                    <span className="bg-white/10 text-slate-400 text-xs py-0.5 px-2 rounded-full font-medium">{SAVED_COMPONENTS.length}</span>
                </h2>

                {/* ------ Components Main ------ */}
                <div className="flex flex-col md:flex-row gap-4 md:gap-6 flex-1 h-full">
                    
                    {/* ---- Left Sidebar: Component List ---- */}
                    <aside className="w-full md:w-72 shrink-0 flex flex-row md:flex-col gap-3 overflow-x-auto md:overflow-y-auto custom-scrollbar pb-2 md:pb-0">
                    {SAVED_COMPONENTS.map((comp) => (
                        <button
                        key={comp.id}
                        onClick={() => setActiveComponent(comp)}
                        className={`shrink-0 w-64 md:w-full text-left p-4 rounded-2xl transition-all duration-300 border ${
                            activeComponent.id === comp.id 
                            ? 'bg-emerald-900/20 border-emerald-500/50 shadow-[0_0_20px_rgba(16,185,129,0.1)]' 
                            : 'bg-white/5 border-white/5 hover:border-white/10 hover:bg-white/10'
                        }`}
                        >
                        <div className="flex justify-between items-start mb-2">
                            <span className="text-[10px] uppercase font-bold text-emerald-500/80 tracking-wider bg-emerald-500/10 px-2 py-0.5 rounded">{comp.category}</span>
                            <span className="text-[10px] text-slate-500">{comp.dateSaved}</span>
                        </div>
                        <h3 className={`text-sm font-semibold mb-1 ${activeComponent.id === comp.id ? 'text-emerald-400' : 'text-slate-200'}`}>
                            {comp.title}
                        </h3>
                        <p className="text-xs text-slate-500 truncate">Tap to view preview & code</p>
                        </button>
                    ))}
                    </aside>

                    {/* ---- Right Area: Preview & Code Detail ---- */}
                    <main className="flex-1 bg-[#00140a]/40 border border-white/5 rounded-3xl backdrop-blur-xl flex flex-col overflow-hidden relative shadow-2xl min-h-100">
                    
                    {/* --- Code / Preview Header --- */}
                    <header className="px-6 py-4 border-b border-white/5 flex flex-wrap items-center justify-between gap-4 bg-white/2">
                        <div className="flex items-center gap-2 bg-[#000502] p-1 rounded-xl border border-white/10">
                            <button 
                                onClick={() => setActiveTab('preview')}
                                className={`px-4 py-1.5 rounded-lg text-sm font-medium transition-all ${activeTab === 'preview' ? 'bg-white/10 text-emerald-400' : 'text-slate-400 hover:text-slate-200'}`}
                            >
                                Preview
                            </button>
                            <button 
                                onClick={() => setActiveTab('code')}
                                className={`px-4 py-1.5 rounded-lg text-sm font-medium transition-all ${activeTab === 'code' ? 'bg-white/10 text-emerald-400' : 'text-slate-400 hover:text-slate-200'}`}
                            >
                                Code
                            </button>
                        </div>

                        <div className="flex items-center gap-2">
                            <button className="p-2 rounded-lg bg-white/5 border border-white/10 text-slate-300 hover:text-emerald-400 hover:border-emerald-500/50 transition-all tooltip-trigger" title="Copy Code">
                                <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M8 16H6a2 2 0 01-2-2V6a2 2 0 012-2h8a2 2 0 012 2v2m-6 12h8a2 2 0 002-2v-8a2 2 0 00-2-2h-8a2 2 0 00-2 2v8a2 2 0 002 2z"></path></svg>
                            </button>
                            <button className="px-4 py-1.5 rounded-lg bg-rose-500/10 text-rose-400 border border-rose-500/20 hover:bg-rose-500/20 text-sm font-medium transition-all flex items-center gap-2">
                                <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16"></path></svg>
                                <span className="hidden sm:inline">Remove</span>
                            </button>
                        </div>
                    </header>

                    {/* -------- Main Render Area ------- */}
                    {/* ---- Code / Preview Section ----- */}
                    <div className="flex-1 relative overflow-hidden flex items-center justify-center bg-[#000502]/60">
                        
                        {/* Dot grid background for Preview */}
                        {activeTab === 'preview' && (
                            <div className="absolute inset-0 opacity-[0.04] pointer-events-none" style={{ backgroundImage: 'radial-gradient(circle at 2px 2px, white 1px, transparent 0)', backgroundSize: '24px 24px' }}></div>
                        )}

                        {/* --- Component Preview Section --- */}
                        {/* ------------- Preview ----------- */}
                        {activeTab === 'preview' && (
                        <div className="relative z-10 w-full h-full flex items-center justify-center p-6 overflow-auto">
                            {activeComponent.preview}
                        </div>
                        )}

                        {/* --- Component Code Section --- */}
                        {/* ------------- Code ----------- */}
                        {activeTab === 'code' && (
                        <div className="w-full h-full bg-[#0d1117] overflow-auto p-4 md:p-6 relative">
                            <div className="absolute top-4 right-4 text-xs text-slate-500 font-mono">React / Tailwind</div>
                            <pre className="text-sm font-mono text-emerald-300/80 leading-relaxed whitespace-pre-wrap sm:whitespace-pre">
                                <code>{activeComponent.code}</code>
                            </pre>
                        </div>
                        )}

                    </div>
                    
                    </main>

                </div>

            </section>

        </div>

    </div>
    
  );
};

export default Profile;